"""
generate_puzzles.py
────────────────────────────────────────────────────────────
hub_words_min4.json'dan geçerli HubPuzzle'lar üretir.

Kural: hub + neighbor gerçekten birleşen bir compound
word/phrase oluşturmalı (goalPOST, POSTcard gibi).

Çıktı: lib/data/hub_puzzles.dart (Dart kodu)

Usage:
    python scripts/generate_puzzles.py
"""

import json

INPUT = "hub_words_min4.json"
OUTPUT = "lib/data/hub_puzzles.dart"

# ─── Elle küratlenmiş puzzle seti ────────────────────────────
# Format: { hub: [neighbor1, neighbor2, neighbor3, neighbor4, ...] }
# Neighborlar hub ile GERÇEKTEN birleşenler.
# Hub önce veya sonra gelebilir: POST+card, goal+POST
CURATED: dict[str, list[str]] = {
    "POST": ["Goal", "Guard", "Office", "Card", "Box", "Mark", "Man", "Script"],
    "FIRE": ["Camp", "Works", "Place", "Alarm", "Man", "Side", "Fly", "Arm"],
    "WATER": ["Fall", "Melon", "Color", "Gun", "Proof", "Ski", "Mark", "Pipe"],
    "BOOK": ["Mark", "Store", "Shelf", "Case", "Worm", "Club", "Fair", "End"],
    "PAPER": ["Work", "Back", "Weight", "Clip", "Back", "Trail", "Towel", "Cut"],
    "LIGHT": ["Sun", "Moon", "Star", "Day", "Spot", "House", "Weight", "Bulb"],
    "HOUSE": ["Tree", "Full", "Hold", "Keeper", "Wife", "Plant", "Work", "Fly"],
    "BACK": ["Pack", "Ground", "Stage", "Yard", "Bone", "Fire", "Track", "Door"],
    "OVER": ["Turn", "Time", "All", "Come", "Look", "Load", "Due", "Lap"],
    "HAND": ["Shake", "Made", "Gun", "Book", "Bag", "Rail", "Craft", "Out"],
    "BALL": ["Foot", "Basket", "Base", "Volley", "Fire", "Pin", "Gum", "Park"],
    "BOARD": ["Card", "Key", "Skate", "Over", "Cup", "Walk", "Game", "Bill"],
    "LINE": ["Dead", "Air", "Hair", "Pipe", "Time", "Out", "Up", "Off"],
    "DOWN": ["Count", "Show", "Town", "Turn", "Fall", "Load", "Pour", "Grade"],
    "PLAY": ["Fair", "Ground", "Room", "Back", "Boy", "Mate", "Time", "Thing"],
    "TIME": ["Over", "Part", "Full", "Pass", "Out", "Bed", "Day", "Life"],
    "WORK": ["Net", "Shop", "Out", "Place", "Load", "Force", "Flow", "Horse"],
    "GAME": ["Board", "Ball", "Over", "Plan", "Show", "Night", "Bird", "Play"],
    "DOOR": ["Back", "Side", "Bell", "Step", "Way", "Man", "Knob", "Mat"],
    "NIGHT": ["Mid", "Over", "Good", "Date", "Club", "Life", "Cap", "Owl"],
    "BOOK": ["Note", "Cook", "Text", "Year", "Guide", "Hand", "Phone", "Face"],
    "BLACK": ["Bird", "Berry", "Board", "Out", "Smith", "List", "Mail", "Belt"],
    "COLD": ["Stone", "Weather", "Blood", "War", "Shoulder", "Feet", "Snap", "Brew"],
    "CARD": ["Post", "Board", "Wild", "Credit", "Gift", "Flash", "Report", "Place"],
    "SPACE": ["Out", "Ship", "Craft", "Walk", "Man", "Time", "Air", "Junk"],
    "ROAD": ["Rail", "Side", "Block", "Map", "Show", "Trip", "Kill", "Runner"],
    "SCHOOL": ["High", "Pre", "Home", "After", "Bus", "Boy", "Girl", "Work"],
    "AIR": ["Port", "Line", "Field", "Craft", "Ship", "Mail", "Fare", "Drop"],
    "SEA": ["Side", "Bird", "Horse", "Shell", "Weed", "Food", "Shore", "Man"],
    "FOOT": ["Ball", "Print", "Step", "Wear", "Path", "Rest", "Note", "Hold"],
    "STAR": ["Fish", "Light", "Gazer", "Ship", "Board", "War", "Dust", "Born"],
    "HEAD": ["Band", "Line", "Ache", "Quarter", "Master", "Phone", "First", "Hunt"],
    "GOLD": ["Fish", "Mine", "Smith", "Rush", "Field", "Finch", "Leaf", "Lock"],
    "BLUE": ["Bird", "Berry", "Bell", "Print", "Tooth", "Bell", "Cap", "Jay"],
    "SUN": ["Flower", "Shine", "Light", "Set", "Rise", "Burn", "Glasses", "Screen"],
    "RAIN": ["Bow", "Drop", "Fall", "Coat", "Forest", "Water", "Cloud", "Storm"],
    "MOON": ["Light", "Shine", "Walk", "Rise", "Set", "Beam", "Stone", "Flower"],
    "SNOW": ["Ball", "Flake", "Fall", "Board", "Storm", "Man", "Drop", "Drift"],
    "WIND": ["Mill", "Shield", "Fall", "Pipe", "Surf", "Bag", "Breaker", "Farm"],
    "SAND": ["Stone", "Storm", "Bank", "Paper", "Castle", "Bar", "Man", "Bag"],
}


DIFFICULTY = {
    # easy: concrete, physical, obvious combinations
    "easy": ["FIRE", "SNOW", "RAIN", "BALL", "MOON", "SUN", "GOLD", "BLUE",
             "STAR", "WATER", "DOOR", "ROAD", "SEA"],
    # medium: common but requires thinking
    "medium": ["POST", "BOOK", "BACK", "HOUSE", "HAND", "NIGHT", "BLACK",
               "COLD", "LIGHT", "HEAD", "SCHOOL", "AIR", "FOOT", "SAND", "WIND"],
    # hard: abstract, many possibilities
    "hard": ["OVER", "DOWN", "TIME", "WORK", "GAME", "LINE", "PLAY",
             "BOARD", "CARD", "SPACE", "PAPER"],
}

def get_difficulty(hub: str) -> str:
    for diff, hubs in DIFFICULTY.items():
        if hub in hubs:
            return diff
    return "medium"


def dart_string_list(items: list[str]) -> str:
    inner = ", ".join(f'"{w}"' for w in items)
    return f"[{inner}]"


def generate_dart(puzzles: dict) -> str:
    lines = [
        "// AUTO-GENERATED by scripts/generate_puzzles.py",
        "// Do not edit manually.",
        "",
        "import '../models/hub_puzzle.dart';",
        "",
        "final List<HubPuzzle> allHubPuzzles = [",
    ]

    for hub, neighbors in puzzles.items():
        diff = get_difficulty(hub)
        lines.append(f"  HubPuzzle(")
        lines.append(f"    hub: \"{hub}\",")
        lines.append(f"    neighbors: {dart_string_list(neighbors)},")
        lines.append(f"    difficulty: Difficulty.{diff},")
        lines.append(f"  ),")

    lines.append("];")
    return "\n".join(lines)


def main():
    print(f"Generating {len(CURATED)} hub puzzles …")
    dart_code = generate_dart(CURATED)

    with open(OUTPUT, "w", encoding="utf-8") as f:
        f.write(dart_code)

    print(f"✓ Written to {OUTPUT}")

    # Stats
    for diff in ["easy", "medium", "hard"]:
        count = sum(1 for h in CURATED if get_difficulty(h) == diff)
        print(f"  {diff}: {count} puzzles")


if __name__ == "__main__":
    main()
