begin;
create temporary table _technology_stage_3 (id uuid primary key,text_en text not null,answer bigint not null,answer_unit text not null,difficulty integer not null,source text not null) on commit drop;
insert into _technology_stage_3 (id,text_en,answer,answer_unit,difficulty,source)
select md5('bets-and-guesses|technology|3|' || v.text_en)::uuid,v.text_en,v.answer,v.answer_unit,v.difficulty,v.source from (values
('How many bits wide was the Intel 4004 processor?',4,'bits',2,'Intel processor history'),
('In what year was the Intel 4004 introduced?',1971,'year',2,'Intel processor history'),
('How many bits wide was the Intel 8080 processor?',8,'bits',2,'Intel processor history'),
('In what year was the Intel 8080 introduced?',1974,'year',2,'Intel processor history'),
('How many bits wide is the x86-64 architecture''s general-purpose register width?',64,'bits',2,'AMD64 architecture'),
('How many cores did the original Apple M1 CPU contain?',8,'CPU cores',2,'Apple M1 technical specifications'),
('How many high-performance CPU cores did the original Apple M1 contain?',4,'cores',3,'Apple M1 technical specifications'),
('How many high-efficiency CPU cores did the original Apple M1 contain?',4,'cores',3,'Apple M1 technical specifications'),
('How many GPU cores were available in the top original Apple M1 configuration?',8,'GPU cores',3,'Apple M1 technical specifications'),
('How many transistors did Apple state the original M1 chip contained in billions?',16,'billion transistors',3,'Apple M1 announcement'),
('How many nanometers was the manufacturing process used for the original Apple M1?',5,'nanometers',2,'Apple M1 announcement'),
('How many megabytes are on a standard single-layer CD-ROM using the common 700 MB capacity?',700,'MB',1,'Compact Disc capacity convention'),
('How many gigabytes can a single-layer DVD hold approximately?',5,'GB',1,'DVD Forum capacity specifications'),
('How many gigabytes can a dual-layer DVD hold approximately?',9,'GB',2,'DVD Forum capacity specifications'),
('How many gigabytes can a single-layer Blu-ray Disc hold?',25,'GB',1,'Blu-ray Disc Association specifications'),
('How many gigabytes can a dual-layer Blu-ray Disc hold?',50,'GB',1,'Blu-ray Disc Association specifications'),
('How many megabytes was the standard capacity of a 3.5-inch high-density floppy disk?',1440,'KB',2,'IBM PC floppy disk format'),
('How many sectors are on a traditional 1.44 MB 3.5-inch floppy disk?',2880,'sectors',4,'IBM PC floppy disk format'),
('How many bytes are in a traditional floppy disk sector?',512,'bytes',3,'IBM PC floppy disk format'),
('How many pins does a standard SATA data connector have?',7,'pins',2,'Serial ATA specification'),
('How many pins does a standard SATA power connector have?',15,'pins',2,'Serial ATA specification'),
('How many gigabits per second is the raw signaling rate of SATA III?',6,'Gbps',2,'Serial ATA Revision 3.0'),
('How many lanes can a standard PCI Express x16 slot provide?',16,'lanes',1,'PCI-SIG specification'),
('How many gigatransfers per second per lane does PCI Express 3.0 use?',8,'GT/s',3,'PCI Express 3.0 specification'),
('How many gigatransfers per second per lane does PCI Express 4.0 use?',16,'GT/s',3,'PCI Express 4.0 specification'),
('How many gigatransfers per second per lane does PCI Express 5.0 use?',32,'GT/s',3,'PCI Express 5.0 specification'),
('How many gigatransfers per second per lane does PCI Express 6.0 use?',64,'GT/s',4,'PCI Express 6.0 specification'),
('How many pins are on a standard desktop DDR4 DIMM?',288,'pins',2,'JEDEC DDR4 specification'),
('How many pins are on a standard desktop DDR3 DIMM?',240,'pins',2,'JEDEC DDR3 specification'),
('How many pins are on a standard desktop DDR2 DIMM?',240,'pins',3,'JEDEC DDR2 specification'),
('How many pins are on a standard desktop DDR5 DIMM?',288,'pins',2,'JEDEC DDR5 specification'),
('How many bits wide is the standard data bus of a non-ECC desktop DIMM?',64,'bits',3,'JEDEC memory architecture'),
('How many bits wide is the data bus of a typical ECC DIMM including parity bits?',72,'bits',3,'JEDEC memory architecture'),
('How many cells are in a standard lithium-ion battery pack rated as 3S?',3,'cells',2,'battery pack notation'),
('How many volts is the nominal voltage of a single lithium-ion cell when rounded to one decimal place times ten?',37,'tenths of a volt',2,'lithium-ion cell convention'),
('How many volts is a typical USB 2.0 power rail?',5,'volts',1,'USB 2.0 specification'),
('How many volts is a standard automotive 12-volt electrical system nominally rated at?',12,'volts',1,'automotive electrical convention'),
('How many cylinders did the original Ford Model T engine have?',4,'cylinders',2,'Ford Model T history'),
('In what year did Ford begin production of the Model T?',1908,'year',1,'Ford Motor Company history'),
('In what year did Boeing''s 747 first enter commercial service?',1970,'year',2,'Boeing 747 history'),
('How many engines does a Boeing 747 have?',4,'engines',1,'Boeing 747 specifications'),
('How many engines does a Boeing 787 Dreamliner have?',2,'engines',1,'Boeing 787 specifications'),
('How many engines does an Airbus A380 have?',4,'engines',1,'Airbus A380 specifications'),
('How many passenger decks run the full length of an Airbus A380?',2,'decks',2,'Airbus A380 specifications'),
('In what year did the Concorde enter commercial passenger service?',1976,'year',2,'Concorde history'),
('How many engines did Concorde have?',4,'engines',2,'Concorde specifications'),
('How many watts is one kilowatt?',1000,'watts',1,'SI units'),
('How many kilowatts are in one megawatt?',1000,'kilowatts',1,'SI units'),
('How many megawatts are in one gigawatt?',1000,'megawatts',1,'SI units'),
('How many hertz are in one gigahertz?',1000000000,'hertz',2,'SI units')
) as v(text_en,answer,answer_unit,difficulty,source);
do $$ declare v_rows int;v_texts int;v_collisions int;v_ids int; begin select count(*),count(distinct lower(btrim(text_en))) into v_rows,v_texts from _technology_stage_3; if v_rows<>50 or v_texts<>50 then raise exception 'Technology batch 3 staging invalid'; end if; if exists(select 1 from _technology_stage_3 where btrim(text_en)='' or answer<=0 or btrim(answer_unit)='' or difficulty not between 1 and 5 or btrim(source)='') then raise exception 'Technology batch 3 invalid content'; end if; select count(*) into v_ids from _technology_stage_3 s join public.questions q on q.id=s.id; if v_ids<>0 then raise exception 'Technology batch 3 UUID collisions: %',v_ids; end if; select count(*) into v_collisions from _technology_stage_3 s join public.questions q on lower(btrim(q.text_en))=lower(btrim(s.text_en)); if v_collisions<>0 then raise exception 'Technology batch 3 wording collisions: %',v_collisions; end if; end $$;
insert into public.questions(id,text_tr,text_en,answer,answer_unit,category,difficulty,source,access_tier) select id,text_en,text_en,answer,answer_unit,'Technology',difficulty,source,'premium' from _technology_stage_3;
do $$ declare v_inserted int; begin select count(*) into v_inserted from public.questions q join _technology_stage_3 s on s.id=q.id; if v_inserted<>50 then raise exception 'Technology batch 3 inserted %',v_inserted; end if; end $$;
commit;