begin;
create temporary table _history_stage_2 (id uuid primary key,text_en text not null,answer bigint not null,answer_unit text not null,difficulty integer not null,source text not null) on commit drop;
insert into _history_stage_2 (id,text_en,answer,answer_unit,difficulty,source)
select md5('bets-and-guesses|history|2|' || v.text_en)::uuid,v.text_en,v.answer,v.answer_unit,v.difficulty,v.source from (values
('In what year did Germany unify as the German Empire?',1871,'year',2,'Encyclopaedia Britannica'),
('In what year did the Meiji Restoration begin in Japan?',1868,'year',2,'Encyclopaedia Britannica'),
('In what year did the Suez Canal officially open?',1869,'year',2,'Encyclopaedia Britannica'),
('In what year did Alexander Graham Bell receive his first U.S. telephone patent?',1876,'year',2,'U.S. Patent and Trademark Office'),
('In what year did Thomas Edison demonstrate a practical incandescent light bulb?',1879,'year',2,'Smithsonian Institution'),
('In what year did the Berlin Conference on Africa begin?',1884,'year',3,'Encyclopaedia Britannica'),
('In what year was the Eiffel Tower completed?',1889,'year',1,'Eiffel Tower official history'),
('In what year did the First Sino-Japanese War begin?',1894,'year',3,'Encyclopaedia Britannica'),
('In what year was the International Olympic Committee founded?',1894,'year',2,'International Olympic Committee'),
('In what year did the Spanish-American War begin?',1898,'year',2,'U.S. National Archives'),
('In what year did the Boxer Rebellion begin in China?',1899,'year',3,'Encyclopaedia Britannica'),
('In what year did Queen Victoria die?',1901,'year',2,'Royal Household historical records'),
('In what year did the Wright brothers make their first powered flight?',1903,'year',1,'Smithsonian Institution'),
('In what year did the Russo-Japanese War begin?',1904,'year',2,'Encyclopaedia Britannica'),
('In what year did the Russian Revolution of 1905 begin?',1905,'year',2,'Encyclopaedia Britannica'),
('In what year did the Young Turk Revolution take place in the Ottoman Empire?',1908,'year',3,'Encyclopaedia Britannica'),
('In what year did the Mexican Revolution begin?',1910,'year',2,'Encyclopaedia Britannica'),
('In what year did the Xinhai Revolution overthrow the Qing dynasty?',1911,'year',2,'Encyclopaedia Britannica'),
('In what year did the Balkan Wars begin?',1912,'year',2,'Encyclopaedia Britannica'),
('In what year did World War I begin?',1914,'year',1,'Imperial War Museums'),
('In what year did the Gallipoli Campaign begin?',1915,'year',2,'Commonwealth War Graves Commission'),
('In what year did the Easter Rising take place in Dublin?',1916,'year',3,'National Archives of Ireland'),
('In what year did the Russian February and October Revolutions take place?',1917,'year',1,'Encyclopaedia Britannica'),
('In what year did World War I end?',1918,'year',1,'Imperial War Museums'),
('In what year was the Treaty of Versailles signed?',1919,'year',1,'U.S. Office of the Historian'),
('In what year was the League of Nations established?',1920,'year',2,'United Nations historical records'),
('In what year was the Republic of Turkey proclaimed?',1923,'year',1,'Republic of Türkiye historical records'),
('In what year did Lenin die?',1924,'year',2,'Encyclopaedia Britannica'),
('In what year did the United Kingdom general strike occur?',1926,'year',3,'UK National Archives'),
('In what year did Charles Lindbergh complete the first solo nonstop transatlantic flight?',1927,'year',2,'Smithsonian Institution'),
('In what year did the Wall Street Crash begin?',1929,'year',1,'Federal Reserve History'),
('In what year did the Salt March led by Mahatma Gandhi begin?',1930,'year',2,'Encyclopaedia Britannica'),
('In what year did Japan invade Manchuria?',1931,'year',2,'Encyclopaedia Britannica'),
('In what year did Franklin D. Roosevelt first take office as U.S. president?',1933,'year',2,'U.S. National Archives'),
('In what year did the Long March of the Chinese Communist forces begin?',1934,'year',3,'Encyclopaedia Britannica'),
('In what year did the Nuremberg Laws take effect in Nazi Germany?',1935,'year',3,'United States Holocaust Memorial Museum'),
('In what year did the Spanish Civil War begin?',1936,'year',1,'Encyclopaedia Britannica'),
('In what year did the Second Sino-Japanese War begin?',1937,'year',2,'Encyclopaedia Britannica'),
('In what year did Germany annex Austria in the Anschluss?',1938,'year',2,'United States Holocaust Memorial Museum'),
('In what year did World War II begin in Europe?',1939,'year',1,'Imperial War Museums'),
('In what year did Germany invade Denmark and Norway?',1940,'year',3,'Imperial War Museums'),
('In what year did Germany launch Operation Barbarossa against the Soviet Union?',1941,'year',2,'Imperial War Museums'),
('In what year did the Battle of Midway take place?',1942,'year',2,'U.S. Naval History and Heritage Command'),
('In what year did the Warsaw Ghetto Uprising take place?',1943,'year',3,'United States Holocaust Memorial Museum'),
('In what year did the D-Day landings in Normandy take place?',1944,'year',1,'Imperial War Museums'),
('In what year did World War II end?',1945,'year',1,'United Nations historical records'),
('In what year was the United Nations formally established?',1945,'year',1,'United Nations'),
('In what year did India gain independence from British rule?',1947,'year',1,'UK National Archives'),
('In what year was the State of Israel declared?',1948,'year',2,'Israel State Archives'),
('In what year was the People''s Republic of China proclaimed?',1949,'year',1,'Encyclopaedia Britannica')
) as v(text_en,answer,answer_unit,difficulty,source);
do $$ declare v_rows int;v_texts int;v_collisions int;v_ids int; begin select count(*),count(distinct lower(btrim(text_en))) into v_rows,v_texts from _history_stage_2; if v_rows<>50 or v_texts<>50 then raise exception 'History batch 2 staging invalid'; end if; if exists(select 1 from _history_stage_2 where btrim(text_en)='' or answer<=0 or btrim(answer_unit)='' or difficulty not between 1 and 5 or btrim(source)='') then raise exception 'History batch 2 invalid content'; end if; select count(*) into v_ids from _history_stage_2 s join public.questions q on q.id=s.id; if v_ids<>0 then raise exception 'History batch 2 UUID collisions: %',v_ids; end if; select count(*) into v_collisions from _history_stage_2 s join public.questions q on lower(btrim(q.text_en))=lower(btrim(s.text_en)); if v_collisions<>0 then raise exception 'History batch 2 wording collisions: %',v_collisions; end if; end $$;
insert into public.questions(id,text_tr,text_en,answer,answer_unit,category,difficulty,source,access_tier) select id,text_en,text_en,answer,answer_unit,'History',difficulty,source,'premium' from _history_stage_2;
commit;