begin;
create temporary table _history_stage_1 (id uuid primary key,text_en text not null,answer bigint not null,answer_unit text not null,difficulty integer not null,source text not null) on commit drop;
insert into _history_stage_1 (id,text_en,answer,answer_unit,difficulty,source)
select md5('bets-and-guesses|history|1|' || v.text_en)::uuid,v.text_en,v.answer,v.answer_unit,v.difficulty,v.source
from (values
('In what year did the Western Roman Empire traditionally fall with the deposition of Romulus Augustulus?',476,'year',2,'Encyclopaedia Britannica'),
('In what year did the Hijra from Mecca to Medina take place?',622,'year',2,'Encyclopaedia Britannica'),
('In what year was Charlemagne crowned emperor in Rome?',800,'year',2,'Encyclopaedia Britannica'),
('In what year was the Battle of Hastings fought?',1066,'year',1,'Encyclopaedia Britannica'),
('In what year did Pope Urban II call for the First Crusade at the Council of Clermont?',1095,'year',3,'Encyclopaedia Britannica'),
('In what year was Magna Carta sealed at Runnymede?',1215,'year',1,'UK Parliament historical records'),
('In what year did Acre fall, marking the end of the major Crusader states in the Holy Land?',1291,'year',4,'Encyclopaedia Britannica'),
('In what year did the Black Death reach Sicily and begin spreading widely through Europe?',1347,'year',3,'Encyclopaedia Britannica'),
('In what year did Constantinople fall to the Ottoman Empire?',1453,'year',1,'Encyclopaedia Britannica'),
('In what year did Christopher Columbus first reach the Americas on his first voyage?',1492,'year',1,'Library of Congress'),
('In what year was the Treaty of Tordesillas signed?',1494,'year',3,'Encyclopaedia Britannica'),
('In what year did Martin Luther publish the Ninety-five Theses?',1517,'year',1,'Encyclopaedia Britannica'),
('In what year did Tenochtitlan fall to the forces led by Hernán Cortés?',1521,'year',2,'Encyclopaedia Britannica'),
('In what year did the English Act of Supremacy recognize Henry VIII as head of the Church of England?',1534,'year',3,'UK Parliament historical records'),
('In what year was Copernicus''s De revolutionibus orbium coelestium published?',1543,'year',3,'Encyclopaedia Britannica'),
('In what year was the Spanish Armada defeated?',1588,'year',1,'Royal Museums Greenwich'),
('In what year was the English East India Company granted its royal charter?',1600,'year',2,'Encyclopaedia Britannica'),
('In what year did Tokugawa Ieyasu establish the Tokugawa shogunate?',1603,'year',2,'Encyclopaedia Britannica'),
('In what year was Jamestown founded as the first permanent English settlement in Virginia?',1607,'year',2,'U.S. National Park Service'),
('In what year did the Thirty Years'' War begin?',1618,'year',2,'Encyclopaedia Britannica'),
('In what year did the Mayflower arrive in New England?',1620,'year',1,'Library of Congress'),
('In what year did the English Civil War begin?',1642,'year',2,'UK Parliament historical records'),
('In what year was the Peace of Westphalia concluded?',1648,'year',2,'Encyclopaedia Britannica'),
('In what year did the Great Fire of London occur?',1666,'year',1,'Museum of London'),
('In what year was Isaac Newton''s Principia Mathematica first published?',1687,'year',3,'Royal Society'),
('In what year did the Glorious Revolution take place in England?',1688,'year',2,'UK Parliament historical records'),
('In what year did the Acts of Union create the Kingdom of Great Britain?',1707,'year',2,'UK Parliament historical records'),
('In what year did the Seven Years'' War begin?',1756,'year',2,'Encyclopaedia Britannica'),
('In what year did the Treaty of Paris end the Seven Years'' War?',1763,'year',3,'Encyclopaedia Britannica'),
('In what year did the British Parliament pass the Stamp Act for the American colonies?',1765,'year',3,'U.S. National Archives'),
('In what year did the Boston Tea Party take place?',1773,'year',1,'U.S. National Archives'),
('In what year was the United States Declaration of Independence adopted?',1776,'year',1,'U.S. National Archives'),
('In what year did the British surrender at Yorktown during the American Revolution?',1781,'year',2,'U.S. National Park Service'),
('In what year was the Treaty of Paris signed to formally end the American Revolutionary War?',1783,'year',2,'U.S. National Archives'),
('In what year was the United States Constitution signed in Philadelphia?',1787,'year',1,'U.S. National Archives'),
('In what year was the Bastille stormed during the French Revolution?',1789,'year',1,'Encyclopaedia Britannica'),
('In what year was the United States Bill of Rights ratified?',1791,'year',2,'U.S. National Archives'),
('In what year did Napoleon Bonaparte seize power in the Coup of 18 Brumaire?',1799,'year',3,'Encyclopaedia Britannica'),
('In what year did Napoleon Bonaparte crown himself Emperor of the French?',1804,'year',2,'Encyclopaedia Britannica'),
('In what year was the Battle of Trafalgar fought?',1805,'year',2,'Royal Museums Greenwich'),
('In what year did Napoleon invade Russia?',1812,'year',2,'Encyclopaedia Britannica'),
('In what year was Napoleon defeated at the Battle of Waterloo?',1815,'year',1,'Encyclopaedia Britannica'),
('In what year did Mexico achieve independence from Spain?',1821,'year',2,'Encyclopaedia Britannica'),
('In what year did the Belgian Revolution begin?',1830,'year',3,'Encyclopaedia Britannica'),
('In what year did the wave of European revolutions known as the Revolutions of 1848 begin?',1848,'year',2,'Encyclopaedia Britannica'),
('In what year did the Crimean War begin?',1853,'year',2,'Encyclopaedia Britannica'),
('In what year did the Indian Rebellion against British East India Company rule begin?',1857,'year',2,'Encyclopaedia Britannica'),
('In what year did the American Civil War begin?',1861,'year',1,'U.S. National Archives'),
('In what year did the Emancipation Proclamation take effect?',1863,'year',1,'U.S. National Archives'),
('In what year was the Thirteenth Amendment abolishing slavery in the United States ratified?',1865,'year',2,'U.S. National Archives')
) as v(text_en,answer,answer_unit,difficulty,source);
do $$ declare v_rows int;v_texts int;v_collisions int;v_ids int; begin select count(*),count(distinct lower(btrim(text_en))) into v_rows,v_texts from _history_stage_1; if v_rows<>50 or v_texts<>50 then raise exception 'History batch 1 staging invalid'; end if; if exists(select 1 from _history_stage_1 where btrim(text_en)='' or answer<=0 or btrim(answer_unit)='' or difficulty not between 1 and 5 or btrim(source)='') then raise exception 'History batch 1 invalid content'; end if; select count(*) into v_ids from _history_stage_1 s join public.questions q on q.id=s.id; if v_ids<>0 then raise exception 'History batch 1 UUID collisions: %',v_ids; end if; select count(*) into v_collisions from _history_stage_1 s join public.questions q on lower(btrim(q.text_en))=lower(btrim(s.text_en)); if v_collisions<>0 then raise exception 'History batch 1 wording collisions: %',v_collisions; end if; end $$;
insert into public.questions(id,text_tr,text_en,answer,answer_unit,category,difficulty,source,access_tier) select id,text_en,text_en,answer,answer_unit,'History',difficulty,source,'premium' from _history_stage_1;
commit;