begin;
create temporary table _technology_stage_2 (id uuid primary key,text_en text not null,answer bigint not null,answer_unit text not null,difficulty integer not null,source text not null) on commit drop;
insert into _technology_stage_2 (id,text_en,answer,answer_unit,difficulty,source)
select md5('bets-and-guesses|technology|2|' || v.text_en)::uuid,v.text_en,v.answer,v.answer_unit,v.difficulty,v.source from (values
('How many layers are in the OSI networking model?',7,'layers',1,'ISO/IEC 7498-1'),
('How many layers are commonly shown in the TCP/IP model?',4,'layers',2,'IETF networking model'),
('How many bits are in a standard TCP port number?',16,'bits',2,'IETF TCP specification'),
('How many possible TCP port numbers exist?',65536,'ports',2,'IETF TCP specification'),
('What is the default TCP port number for HTTP?',80,'port',1,'IANA service name registry'),
('What is the default TCP port number for HTTPS?',443,'port',1,'IANA service name registry'),
('What is the default TCP port number for SSH?',22,'port',1,'IANA service name registry'),
('What is the default TCP port number for SMTP?',25,'port',2,'IANA service name registry'),
('What is the default port number for DNS?',53,'port',1,'IANA service name registry'),
('What is the default TCP port number for FTP control?',21,'port',2,'IANA service name registry'),
('What is the default TCP port number for IMAP?',143,'port',2,'IANA service name registry'),
('What is the default TCP port number for secure IMAP?',993,'port',2,'IANA service name registry'),
('What is the default TCP port number for POP3?',110,'port',2,'IANA service name registry'),
('What is the default TCP port number for secure POP3?',995,'port',2,'IANA service name registry'),
('How many bits are in the port number field of a UDP header?',16,'bits',3,'IETF RFC 768'),
('How many bytes long is the fixed UDP header?',8,'bytes',3,'IETF RFC 768'),
('How many bytes is the minimum IPv4 header without options?',20,'bytes',3,'IETF RFC 791'),
('How many bytes is the fixed IPv6 base header?',40,'bytes',3,'IETF RFC 8200'),
('How many bytes is the standard Ethernet MAC address length?',6,'bytes',2,'IEEE 802'),
('How many bytes is the Ethernet Frame Check Sequence?',4,'bytes',3,'IEEE 802.3'),
('How many octets are in a standard IPv4 dotted-decimal address?',4,'octets',1,'IETF RFC 791'),
('How many hexadecimal groups are in a fully expanded IPv6 address?',8,'groups',2,'IETF RFC 8200'),
('How many bits are in one IPv6 hexadecimal group?',16,'bits',3,'IETF RFC 8200'),
('How many bits are in one hexadecimal digit?',4,'bits',1,'binary notation'),
('How many symbols are used in hexadecimal notation?',16,'symbols',1,'hexadecimal notation'),
('How many symbols are used in binary notation?',2,'symbols',1,'binary notation'),
('How many bits are in an ASCII character in the original standard?',7,'bits',2,'ANSI ASCII standard'),
('How many code points are in standard 7-bit ASCII?',128,'code points',2,'ANSI ASCII standard'),
('How many bytes can a UTF-8 encoded Unicode scalar value use at most?',4,'bytes',3,'Unicode Standard'),
('How many bits are in a UTF-16 code unit?',16,'bits',2,'Unicode Standard'),
('How many bits are in a UTF-32 code unit?',32,'bits',2,'Unicode Standard'),
('How many characters long is a standard UUID written without hyphens?',32,'hex digits',2,'IETF RFC 9562'),
('How many bits are in a UUID?',128,'bits',1,'IETF RFC 9562'),
('How many hexadecimal digits are in a standard UUID including no hyphens?',32,'hex digits',2,'IETF RFC 9562'),
('How many groups are separated by hyphens in the common textual form of a UUID?',5,'groups',2,'IETF RFC 9562'),
('In what year was the first iPhone introduced?',2007,'year',1,'Apple iPhone history'),
('In what year was the first iPad introduced?',2010,'year',1,'Apple iPad history'),
('In what year did Apple launch the original Macintosh?',1984,'year',1,'Apple Macintosh history'),
('In what year was the IBM Personal Computer introduced?',1981,'year',2,'IBM PC history'),
('In what year was the World Wide Web made publicly available by CERN?',1991,'year',2,'CERN web history'),
('In what year did Tim Berners-Lee submit his first proposal for the World Wide Web?',1989,'year',2,'CERN web history'),
('In what year was the first website at CERN put online?',1991,'year',2,'CERN web history'),
('In what year was Google founded?',1998,'year',1,'Google company history'),
('In what year was Facebook launched?',2004,'year',1,'Meta company history'),
('In what year was YouTube founded?',2005,'year',1,'YouTube company history'),
('In what year was Twitter launched?',2006,'year',1,'Twitter company history'),
('In what year was Android first released commercially?',2008,'year',1,'Android platform history'),
('In what year was the first commercial SMS text message sent?',1992,'year',2,'mobile communications history'),
('In what year was Bluetooth 1.0 formally released?',1999,'year',2,'Bluetooth SIG history'),
('In what year was the Wi-Fi Alliance founded?',1999,'year',3,'Wi-Fi Alliance history')
) as v(text_en,answer,answer_unit,difficulty,source);
do $$ declare v_rows int;v_texts int;v_collisions int;v_ids int; begin select count(*),count(distinct lower(btrim(text_en))) into v_rows,v_texts from _technology_stage_2; if v_rows<>50 or v_texts<>50 then raise exception 'Technology batch 2 staging invalid'; end if; if exists(select 1 from _technology_stage_2 where btrim(text_en)='' or answer<=0 or btrim(answer_unit)='' or difficulty not between 1 and 5 or btrim(source)='') then raise exception 'Technology batch 2 invalid content'; end if; select count(*) into v_ids from _technology_stage_2 s join public.questions q on q.id=s.id; if v_ids<>0 then raise exception 'Technology batch 2 UUID collisions: %',v_ids; end if; select count(*) into v_collisions from _technology_stage_2 s join public.questions q on lower(btrim(q.text_en))=lower(btrim(s.text_en)); if v_collisions<>0 then raise exception 'Technology batch 2 wording collisions: %',v_collisions; end if; end $$;
insert into public.questions(id,text_tr,text_en,answer,answer_unit,category,difficulty,source,access_tier) select id,text_en,text_en,answer,answer_unit,'Technology',difficulty,source,'premium' from _technology_stage_2;
do $$ declare v_inserted int; begin select count(*) into v_inserted from public.questions q join _technology_stage_2 s on s.id=q.id; if v_inserted<>50 then raise exception 'Technology batch 2 inserted %',v_inserted; end if; end $$;
commit;