begin;
create temporary table _technology_stage_1 (id uuid primary key,text_en text not null,answer bigint not null,answer_unit text not null,difficulty integer not null,source text not null) on commit drop;
insert into _technology_stage_1 (id,text_en,answer,answer_unit,difficulty,source)
select md5('bets-and-guesses|technology|1|' || v.text_en)::uuid,v.text_en,v.answer,v.answer_unit,v.difficulty,v.source from (values
('How many bits are in one byte?',8,'bits',1,'IEC binary data conventions'),
('How many bits are in an IPv4 address?',32,'bits',1,'IETF RFC 791'),
('How many bits are in an IPv6 address?',128,'bits',1,'IETF RFC 8200'),
('How many bits are in a standard MAC address?',48,'bits',2,'IEEE 802'),
('How many decimal digits are in a standard IMEI number?',15,'digits',2,'3GPP device identity specifications'),
('How many hexadecimal digits are in a 128-bit IPv6 address when written without separators?',32,'hex digits',3,'IETF RFC 8200'),
('How many bits are in an AES-128 encryption key?',128,'bits',2,'NIST FIPS 197'),
('How many bits are in an AES-256 encryption key?',256,'bits',2,'NIST FIPS 197'),
('How many rounds does AES-128 use?',10,'rounds',3,'NIST FIPS 197'),
('How many rounds does AES-192 use?',12,'rounds',4,'NIST FIPS 197'),
('How many rounds does AES-256 use?',14,'rounds',3,'NIST FIPS 197'),
('How many bits are in a SHA-256 hash output?',256,'bits',2,'NIST FIPS 180-4'),
('How many bits are in a SHA-512 hash output?',512,'bits',2,'NIST FIPS 180-4'),
('How many bytes are in a kibibyte?',1024,'bytes',1,'IEC 80000-13'),
('How many kibibytes are in a mebibyte?',1024,'KiB',1,'IEC 80000-13'),
('How many mebibytes are in a gibibyte?',1024,'MiB',1,'IEC 80000-13'),
('How many gibibytes are in a tebibyte?',1024,'GiB',1,'IEC 80000-13'),
('How many bytes are in a mebibyte?',1048576,'bytes',2,'IEC 80000-13'),
('How many bytes are in a gibibyte?',1073741824,'bytes',3,'IEC 80000-13'),
('How many possible values can an 8-bit unsigned integer represent?',256,'values',2,'binary arithmetic'),
('How many possible values can a 16-bit unsigned integer represent?',65536,'values',2,'binary arithmetic'),
('How many possible values can a 24-bit RGB color encode?',16777216,'colors',2,'digital color representation'),
('How many bits per pixel are used by standard 24-bit RGB color?',24,'bits',1,'digital color representation'),
('How many color channels are used in standard RGB color?',3,'channels',1,'digital color representation'),
('How many bits per channel are used in standard 24-bit RGB color?',8,'bits',1,'digital color representation'),
('How many pixels wide is 1080p Full HD video?',1920,'pixels',1,'HDTV display standards'),
('How many pixels high is 1080p Full HD video?',1080,'pixels',1,'HDTV display standards'),
('How many pixels wide is 720p HD video?',1280,'pixels',1,'HDTV display standards'),
('How many pixels high is 720p HD video?',720,'pixels',1,'HDTV display standards'),
('How many pixels wide is consumer 4K UHD video?',3840,'pixels',1,'UHDTV display standards'),
('How many pixels high is consumer 4K UHD video?',2160,'pixels',1,'UHDTV display standards'),
('How many pixels wide is consumer 8K UHD video?',7680,'pixels',2,'UHDTV display standards'),
('How many pixels high is consumer 8K UHD video?',4320,'pixels',2,'UHDTV display standards'),
('How many total pixels are in a 1920 by 1080 Full HD frame?',2073600,'pixels',2,'HDTV display standards'),
('How many total pixels are in a 3840 by 2160 4K UHD frame?',8294400,'pixels',2,'UHDTV display standards'),
('How many total pixels are in a 7680 by 4320 8K UHD frame?',33177600,'pixels',3,'UHDTV display standards'),
('How many frames per second are in traditional NTSC-derived 60p video rounded to a whole number?',60,'frames per second',1,'video timing conventions'),
('How many hertz is a display refreshing 120 times per second?',120,'hertz',1,'display refresh conventions'),
('How many pins does a standard USB Type-A 2.0 connector use?',4,'pins',2,'USB 2.0 specification'),
('How many pins does a standard USB Type-C receptacle have?',24,'pins',2,'USB Type-C specification'),
('How many gigabits per second is the signaling rate of USB 3.2 Gen 1?',5,'Gbps',2,'USB 3.2 specification'),
('How many gigabits per second is the signaling rate of USB 3.2 Gen 2?',10,'Gbps',2,'USB 3.2 specification'),
('How many gigabits per second is the aggregate signaling rate of USB 3.2 Gen 2x2?',20,'Gbps',3,'USB 3.2 specification'),
('How many gigabits per second can USB4 Version 1.0 reach at its top certified rate?',40,'Gbps',3,'USB4 specification'),
('How many pins are in a standard HDMI Type A connector?',19,'pins',2,'HDMI specification'),
('How many conductors are in a standard RJ45 Ethernet connection?',8,'conductors',1,'Ethernet cabling standards'),
('How many twisted wire pairs are in a standard Ethernet cable?',4,'pairs',1,'Ethernet cabling standards'),
('How many megabits per second is Fast Ethernet?',100,'Mbps',1,'IEEE 802.3u'),
('How many megabits per second is Gigabit Ethernet?',1000,'Mbps',1,'IEEE 802.3ab'),
('How many gigabits per second is 10 Gigabit Ethernet?',10,'Gbps',1,'IEEE 802.3ae')
) as v(text_en,answer,answer_unit,difficulty,source);
do $$ declare v_rows int;v_texts int;v_collisions int;v_ids int; begin select count(*),count(distinct lower(btrim(text_en))) into v_rows,v_texts from _technology_stage_1; if v_rows<>50 or v_texts<>50 then raise exception 'Technology batch 1 staging invalid'; end if; if exists(select 1 from _technology_stage_1 where btrim(text_en)='' or answer<=0 or btrim(answer_unit)='' or difficulty not between 1 and 5 or btrim(source)='') then raise exception 'Technology batch 1 invalid content'; end if; select count(*) into v_ids from _technology_stage_1 s join public.questions q on q.id=s.id; if v_ids<>0 then raise exception 'Technology batch 1 UUID collisions: %',v_ids; end if; select count(*) into v_collisions from _technology_stage_1 s join public.questions q on lower(btrim(q.text_en))=lower(btrim(s.text_en)); if v_collisions<>0 then raise exception 'Technology batch 1 wording collisions: %',v_collisions; end if; end $$;
insert into public.questions(id,text_tr,text_en,answer,answer_unit,category,difficulty,source,access_tier) select id,text_en,text_en,answer,answer_unit,'Technology',difficulty,source,'premium' from _technology_stage_1;
do $$ declare v_inserted int; begin select count(*) into v_inserted from public.questions q join _technology_stage_1 s on s.id=q.id; if v_inserted<>50 then raise exception 'Technology batch 1 inserted %',v_inserted; end if; end $$;
commit;