begin;
create temporary table _history_stage_3 (id uuid primary key,text_en text not null,answer bigint not null,answer_unit text not null,difficulty integer not null,source text not null) on commit drop;
insert into _history_stage_3 (id,text_en,answer,answer_unit,difficulty,source)
select md5('bets-and-guesses|history|3|' || v.text_en)::uuid,v.text_en,v.answer,v.answer_unit,v.difficulty,v.source from (values
('In what year did the Korean War begin?',1950,'year',1,'United Nations Command historical records'),
('In what year was the European Coal and Steel Community founded?',1951,'year',3,'European Union historical records'),
('In what year did Queen Elizabeth II become monarch?',1952,'year',1,'Royal Household historical records'),
('In what year did the Korean War armistice take effect?',1953,'year',2,'United Nations Command historical records'),
('In what year did the Algerian War of Independence begin?',1954,'year',2,'Encyclopaedia Britannica'),
('In what year was the Warsaw Pact established?',1955,'year',2,'NATO historical records'),
('In what year did the Suez Crisis take place?',1956,'year',1,'Encyclopaedia Britannica'),
('In what year did the Soviet Union launch Sputnik 1?',1957,'year',1,'NASA history'),
('In what year was NASA established?',1958,'year',1,'NASA history'),
('In what year did the Cuban Revolution bring Fidel Castro to power?',1959,'year',2,'Encyclopaedia Britannica'),
('In what year did the Congo gain independence from Belgium?',1960,'year',2,'United Nations historical records'),
('In what year was the Berlin Wall built?',1961,'year',1,'German Historical Museum'),
('In what year did the Cuban Missile Crisis take place?',1962,'year',1,'U.S. Office of the Historian'),
('In what year was Martin Luther King Jr.''s March on Washington?',1963,'year',1,'U.S. National Archives'),
('In what year was the U.S. Civil Rights Act signed into law?',1964,'year',1,'U.S. National Archives'),
('In what year did the first large-scale U.S. combat troops arrive in Vietnam?',1965,'year',2,'U.S. National Archives'),
('In what year did the Cultural Revolution begin in China?',1966,'year',2,'Encyclopaedia Britannica'),
('In what year did the Six-Day War take place?',1967,'year',2,'Encyclopaedia Britannica'),
('In what year did the Prague Spring take place?',1968,'year',2,'Encyclopaedia Britannica'),
('In what year did Apollo 11 land humans on the Moon?',1969,'year',1,'NASA history'),
('In what year did the Kent State shootings occur in the United States?',1970,'year',3,'U.S. National Archives'),
('In what year was the People''s Republic of China admitted to the United Nations seat for China?',1971,'year',3,'United Nations historical records'),
('In what year did the Watergate break-in occur?',1972,'year',2,'U.S. National Archives'),
('In what year did the Yom Kippur War begin?',1973,'year',2,'Encyclopaedia Britannica'),
('In what year did Richard Nixon resign as U.S. president?',1974,'year',1,'U.S. National Archives'),
('In what year did the Vietnam War end with the fall of Saigon?',1975,'year',1,'U.S. National Archives'),
('In what year did the Soweto uprising take place in South Africa?',1976,'year',2,'South African History Archive'),
('In what year were the Camp David Accords signed?',1978,'year',2,'U.S. Office of the Historian'),
('In what year did the Iranian Revolution overthrow the monarchy?',1979,'year',1,'Encyclopaedia Britannica'),
('In what year did the Iran-Iraq War begin?',1980,'year',2,'Encyclopaedia Britannica'),
('In what year did the Falklands War take place?',1982,'year',1,'UK National Archives'),
('In what year did the Chernobyl nuclear disaster occur?',1986,'year',1,'International Atomic Energy Agency'),
('In what year was the Intermediate-Range Nuclear Forces Treaty signed?',1987,'year',3,'U.S. Office of the Historian'),
('In what year did the Berlin Wall fall?',1989,'year',1,'German Historical Museum'),
('In what year did Germany reunify?',1990,'year',1,'German Federal Government historical records'),
('In what year did the Soviet Union dissolve?',1991,'year',1,'Encyclopaedia Britannica'),
('In what year was the Maastricht Treaty signed?',1992,'year',2,'European Union historical records'),
('In what year did apartheid-era South Africa hold its first fully democratic national election?',1994,'year',1,'South African government historical records'),
('In what year was the Dayton Agreement initialed to end the Bosnian War?',1995,'year',2,'U.S. Office of the Historian'),
('In what year did Hong Kong return from British to Chinese sovereignty?',1997,'year',1,'UK National Archives'),
('In what year did the euro launch as an accounting currency?',1999,'year',2,'European Central Bank'),
('In what year did the September 11 attacks take place in the United States?',2001,'year',1,'9/11 Commission Report'),
('In what year did the Iraq War begin?',2003,'year',1,'U.S. National Archives'),
('In what year did the Indian Ocean earthquake and tsunami occur?',2004,'year',1,'USGS historical records'),
('In what year did the global financial crisis intensify with the collapse of Lehman Brothers?',2008,'year',1,'Federal Reserve History'),
('In what year did the Arab Spring begin in Tunisia?',2010,'year',2,'Encyclopaedia Britannica'),
('In what year did South Sudan become independent?',2011,'year',2,'United Nations'),
('In what year did the United Kingdom vote in the Brexit referendum?',2016,'year',1,'UK Electoral Commission'),
('In what year did the COVID-19 pandemic lead the World Health Organization to declare a pandemic?',2020,'year',1,'World Health Organization'),
('In what year did the United Kingdom formally leave the European Union?',2020,'year',2,'European Union historical records')
) as v(text_en,answer,answer_unit,difficulty,source);
do $$ declare v_rows int;v_texts int;v_collisions int;v_ids int; begin select count(*),count(distinct lower(btrim(text_en))) into v_rows,v_texts from _history_stage_3; if v_rows<>50 or v_texts<>50 then raise exception 'History batch 3 staging invalid'; end if; if exists(select 1 from _history_stage_3 where btrim(text_en)='' or answer<=0 or btrim(answer_unit)='' or difficulty not between 1 and 5 or btrim(source)='') then raise exception 'History batch 3 invalid content'; end if; select count(*) into v_ids from _history_stage_3 s join public.questions q on q.id=s.id; if v_ids<>0 then raise exception 'History batch 3 UUID collisions: %',v_ids; end if; select count(*) into v_collisions from _history_stage_3 s join public.questions q on lower(btrim(q.text_en))=lower(btrim(s.text_en)); if v_collisions<>0 then raise exception 'History batch 3 wording collisions: %',v_collisions; end if; end $$;
insert into public.questions(id,text_tr,text_en,answer,answer_unit,category,difficulty,source,access_tier) select id,text_en,text_en,answer,answer_unit,'History',difficulty,source,'premium' from _history_stage_3;
commit;